#the data images has plugins and logs dir
FROM alpine:3.8
# me
MAINTAINER andy "rjzjh@163.com"
#
LABEL version="3.0"
LABEL location="Shang Hai" author="andy" role="Data"

RUN addgroup -S duckula && adduser -S -G duckula duckula
RUN set -ex; \
    mkdir -p /data/duckula-data; \
    apk update upgrade; \
    apk add --no-cache --virtual .must  \
         'su-exec>=0.2' \
          bash; \
    apk add --no-cache --virtual .duckuladepent  \
          tar;
COPY ./duckula-data.tar  /data/
RUN for path in \
		 /data/duckula-data \
	; do \
		mkdir -p "$path"; \
		chown -R duckula:duckula "$path"; \
	done; 
#    apk del .duckuladepent; 
VOLUME /data/duckula-data
WORKDIR /data/duckula-data	
COPY ./docker-entrypoint/docker-entrypoint-data.sh  /
RUN set -ex; \
    chmod  +x  /docker-entrypoint-data.sh;
ENTRYPOINT ["/docker-entrypoint-data.sh","/bin/bash"]