
server:
  port: 8080

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  refresh:
    enabled: false

spring:
  #解决Error creating bean with name 'scopedTarget.dataSource': Requested bean is currently in creation: Is  
  cloud:
    refresh:
      refreshable: none       
    

#打印SQL日志
logging:
  level:
    net.wicp.tams.app.duckula.controller.dao: DEBUG    

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 600000
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 600000
  
  
common:
  jdbc:
    datasource:
      default:
        host: localhost
        port: 3307
        username: root
        password: mysql
        defaultdb: duckula