
server:
  port: 8080

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  refresh:
    enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/duckula?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
  #解决Error creating bean with name 'scopedTarget.dataSource': Requested bean is currently in creation: Is  
  cloud:
    refresh:
      refreshable: none       
    
#配置Mybatis
mybatis:
  type-aliases-package: net.wicp.tams.app.duckula.controller.bean.models
  mapper-locations: classpath:mybatis/sqlmap/*.xml
  configuration:
    # 开启驼峰命名转换，如：Table(create_time) -> Entity(createTime)。不需要我们关心怎么进行字段匹配，mybatis会自动识别`大写字母与下划线`
    map-underscore-to-camel-case: true

#打印SQL日志
logging:
  level:
    com.niaobulashi.dao: DEBUG    

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 600000
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 600000
  
  
common:
  jdbc:
    datasource:
      default:
        host: localhost
        port: 3307
        username: root
        password: mysql