
server:
  port: 8080

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  refresh:
    enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/duckula?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
  #解决Error creating bean with name 'scopedTarget.dataSource': Requested bean is currently in creation: Is  
  cloud:
    refresh:
      refreshable: none
mybatis:
  mapper-locations: classpath:mybatis/primary/sqlmap/*.xml        
    

#打印SQL日志
logging:
  level:
    net.wicp.tams.app.duckula.controller.dao: DEBUG    

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 600000
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 600000