package net.wicp.tams.app.duckula.controller.dao;

import java.util.List;
import net.wicp.tams.app.duckula.controller.bean.models.CommonTask;
import net.wicp.tams.app.duckula.controller.bean.models.CommonTaskExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CommonTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    long countByExample(CommonTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int deleteByExample(CommonTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    @Delete({
        "delete from common_task",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    @Insert({
        "insert into common_task (id, name, ",
        "version, namespace, ",
        "rule)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{version,jdbcType=VARCHAR}, #{namespace,jdbcType=VARCHAR}, ",
        "#{rule,jdbcType=VARCHAR})"
    })
    int insert(CommonTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int insertSelective(CommonTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    List<CommonTask> selectByExample(CommonTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name, version, namespace, rule",
        "from common_task",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("net.wicp.tams.app.duckula.controller.dao.CommonTaskMapper.BaseResultMap")
    CommonTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CommonTask record, @Param("example") CommonTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CommonTask record, @Param("example") CommonTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CommonTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    @Update({
        "update common_task",
        "set name = #{name,jdbcType=VARCHAR},",
          "version = #{version,jdbcType=VARCHAR},",
          "namespace = #{namespace,jdbcType=VARCHAR},",
          "rule = #{rule,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CommonTask record);
}