package net.wicp.tams.app.duckula.controller.bean.models;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table common_version
 */
public class CommonVersion {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column common_version.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * Database Column Remarks: 主程序版本 This field was generated by MyBatis Generator. This field corresponds to the database column common_version.main_version
	 * @mbg.generated
	 */
	private String mainVersion;
	/**
	 * Database Column Remarks: 数据版本 This field was generated by MyBatis Generator. This field corresponds to the database column common_version.data_version
	 * @mbg.generated
	 */
	private String dataVersion;
	/**
	 * Database Column Remarks: 作者 This field was generated by MyBatis Generator. This field corresponds to the database column common_version.author
	 * @mbg.generated
	 */
	private String author;
	/**
	 * Database Column Remarks: 升级时间 This field was generated by MyBatis Generator. This field corresponds to the database column common_version.update_time
	 * @mbg.generated
	 */
	private Date updateTime;
	/**
	 * Database Column Remarks: 更新说明 This field was generated by MyBatis Generator. This field corresponds to the database column common_version.readme
	 * @mbg.generated
	 */
	private String readme;
	/**
	 * Database Column Remarks: 存储的云介质，s3，oss This field was generated by MyBatis Generator. This field corresponds to the database column common_version.store_cloud
	 * @mbg.generated
	 */
	private String storeCloud;
	/**
	 * Database Column Remarks: accessKey This field was generated by MyBatis Generator. This field corresponds to the database column common_version.accessKey
	 * @mbg.generated
	 */
	private String accesskey;
	/**
	 * Database Column Remarks: secretKey This field was generated by MyBatis Generator. This field corresponds to the database column common_version.secretKey
	 * @mbg.generated
	 */
	private String secretkey;
	/**
	 * Database Column Remarks: 存储路径 This field was generated by MyBatis Generator. This field corresponds to the database column common_version.path
	 * @mbg.generated
	 */
	private String path;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_version
	 * @mbg.generated
	 */
	public CommonVersion(Integer id, String mainVersion, String dataVersion, String author, Date updateTime,
			String readme, String storeCloud, String accesskey, String secretkey, String path) {
		this.id = id;
		this.mainVersion = mainVersion;
		this.dataVersion = dataVersion;
		this.author = author;
		this.updateTime = updateTime;
		this.readme = readme;
		this.storeCloud = storeCloud;
		this.accesskey = accesskey;
		this.secretkey = secretkey;
		this.path = path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_version
	 * @mbg.generated
	 */
	public CommonVersion() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_version.id
	 * @return  the value of common_version.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_version.id
	 * @param id  the value for common_version.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_version.main_version
	 * @return  the value of common_version.main_version
	 * @mbg.generated
	 */
	public String getMainVersion() {
		return mainVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_version.main_version
	 * @param mainVersion  the value for common_version.main_version
	 * @mbg.generated
	 */
	public void setMainVersion(String mainVersion) {
		this.mainVersion = mainVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_version.data_version
	 * @return  the value of common_version.data_version
	 * @mbg.generated
	 */
	public String getDataVersion() {
		return dataVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_version.data_version
	 * @param dataVersion  the value for common_version.data_version
	 * @mbg.generated
	 */
	public void setDataVersion(String dataVersion) {
		this.dataVersion = dataVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_version.author
	 * @return  the value of common_version.author
	 * @mbg.generated
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_version.author
	 * @param author  the value for common_version.author
	 * @mbg.generated
	 */
	public void setAuthor(String author) {
		this.author = author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_version.update_time
	 * @return  the value of common_version.update_time
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_version.update_time
	 * @param updateTime  the value for common_version.update_time
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_version.readme
	 * @return  the value of common_version.readme
	 * @mbg.generated
	 */
	public String getReadme() {
		return readme;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_version.readme
	 * @param readme  the value for common_version.readme
	 * @mbg.generated
	 */
	public void setReadme(String readme) {
		this.readme = readme;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_version.store_cloud
	 * @return  the value of common_version.store_cloud
	 * @mbg.generated
	 */
	public String getStoreCloud() {
		return storeCloud;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_version.store_cloud
	 * @param storeCloud  the value for common_version.store_cloud
	 * @mbg.generated
	 */
	public void setStoreCloud(String storeCloud) {
		this.storeCloud = storeCloud;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_version.accessKey
	 * @return  the value of common_version.accessKey
	 * @mbg.generated
	 */
	public String getAccesskey() {
		return accesskey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_version.accessKey
	 * @param accesskey  the value for common_version.accessKey
	 * @mbg.generated
	 */
	public void setAccesskey(String accesskey) {
		this.accesskey = accesskey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_version.secretKey
	 * @return  the value of common_version.secretKey
	 * @mbg.generated
	 */
	public String getSecretkey() {
		return secretkey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_version.secretKey
	 * @param secretkey  the value for common_version.secretKey
	 * @mbg.generated
	 */
	public void setSecretkey(String secretkey) {
		this.secretkey = secretkey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_version.path
	 * @return  the value of common_version.path
	 * @mbg.generated
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_version.path
	 * @param path  the value for common_version.path
	 * @mbg.generated
	 */
	public void setPath(String path) {
		this.path = path;
	}
}