package net.wicp.tams.app.duckula.controller.bean.models;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table common_deploy
 */
public class CommonDeploy {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * Database Column Remarks: 部署类型:  k8s/docker/host This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.deploy
	 * @mbg.generated
	 */
	private String deploy;
	/**
	 * Database Column Remarks: 环境：开发/测试/预发/演示/生产 This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.env
	 * @mbg.generated
	 */
	private String env;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.url
	 * @mbg.generated
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.token
	 * @mbg.generated
	 */
	private String token;
	/**
	 * Database Column Remarks: config配置文件 This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.config
	 * @mbg.generated
	 */
	private String config;
	/**
	 * Database Column Remarks: 用户名，deploy为host才启作用 This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.host
	 * @mbg.generated
	 */
	private String host;
	/**
	 * Database Column Remarks: 密码 This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.pwd
	 * @mbg.generated
	 */
	private String pwd;
	/**
	 * Database Column Remarks: 备注 This field was generated by MyBatis Generator. This field corresponds to the database column common_deploy.remark
	 * @mbg.generated
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_deploy
	 * @mbg.generated
	 */
	public CommonDeploy(Long id, String name, String deploy, String env, String url, String token, String config,
			String host, String pwd, String remark) {
		this.id = id;
		this.name = name;
		this.deploy = deploy;
		this.env = env;
		this.url = url;
		this.token = token;
		this.config = config;
		this.host = host;
		this.pwd = pwd;
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_deploy
	 * @mbg.generated
	 */
	public CommonDeploy() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.id
	 * @return  the value of common_deploy.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.id
	 * @param id  the value for common_deploy.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.name
	 * @return  the value of common_deploy.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.name
	 * @param name  the value for common_deploy.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.deploy
	 * @return  the value of common_deploy.deploy
	 * @mbg.generated
	 */
	public String getDeploy() {
		return deploy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.deploy
	 * @param deploy  the value for common_deploy.deploy
	 * @mbg.generated
	 */
	public void setDeploy(String deploy) {
		this.deploy = deploy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.env
	 * @return  the value of common_deploy.env
	 * @mbg.generated
	 */
	public String getEnv() {
		return env;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.env
	 * @param env  the value for common_deploy.env
	 * @mbg.generated
	 */
	public void setEnv(String env) {
		this.env = env;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.url
	 * @return  the value of common_deploy.url
	 * @mbg.generated
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.url
	 * @param url  the value for common_deploy.url
	 * @mbg.generated
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.token
	 * @return  the value of common_deploy.token
	 * @mbg.generated
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.token
	 * @param token  the value for common_deploy.token
	 * @mbg.generated
	 */
	public void setToken(String token) {
		this.token = token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.config
	 * @return  the value of common_deploy.config
	 * @mbg.generated
	 */
	public String getConfig() {
		return config;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.config
	 * @param config  the value for common_deploy.config
	 * @mbg.generated
	 */
	public void setConfig(String config) {
		this.config = config;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.host
	 * @return  the value of common_deploy.host
	 * @mbg.generated
	 */
	public String getHost() {
		return host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.host
	 * @param host  the value for common_deploy.host
	 * @mbg.generated
	 */
	public void setHost(String host) {
		this.host = host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.pwd
	 * @return  the value of common_deploy.pwd
	 * @mbg.generated
	 */
	public String getPwd() {
		return pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.pwd
	 * @param pwd  the value for common_deploy.pwd
	 * @mbg.generated
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_deploy.remark
	 * @return  the value of common_deploy.remark
	 * @mbg.generated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_deploy.remark
	 * @param remark  the value for common_deploy.remark
	 * @mbg.generated
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}