package net.wicp.tams.app.duckula.controller.bean.models;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table common_task
 */
public class CommonTask {

	/**
	 * Database Column Remarks: id This field was generated by MyBatis Generator. This field corresponds to the database column common_task.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * Database Column Remarks: 监听名称 This field was generated by MyBatis Generator. This field corresponds to the database column common_task.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * Database Column Remarks: duckula监听的版本 This field was generated by MyBatis Generator. This field corresponds to the database column common_task.version
	 * @mbg.generated
	 */
	private String version;
	/**
	 * Database Column Remarks: 规则 This field was generated by MyBatis Generator. This field corresponds to the database column common_task.rule
	 * @mbg.generated
	 */
	private String rule;
	/**
	 * Database Column Remarks: 部署ID配置 This field was generated by MyBatis Generator. This field corresponds to the database column common_task.deploy_id
	 * @mbg.generated
	 */
	private Long deployId;
	/**
	 * Database Column Remarks: 用户id This field was generated by MyBatis Generator. This field corresponds to the database column common_task.user_id
	 * @mbg.generated
	 */
	private Long userId;
	/**
	 * Database Column Remarks: 目的中间件配置 This field was generated by MyBatis Generator. This field corresponds to the database column common_task.middleware_id
	 * @mbg.generated
	 */
	private Long middlewareId;
	/**
	 * Database Column Remarks: 需要监听的实例配置 This field was generated by MyBatis Generator. This field corresponds to the database column common_task.instance_id
	 * @mbg.generated
	 */
	private Long instanceId;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_task
	 * @mbg.generated
	 */
	public CommonTask(Long id, String name, String version, String rule, Long deployId, Long userId, Long middlewareId,
			Long instanceId) {
		this.id = id;
		this.name = name;
		this.version = version;
		this.rule = rule;
		this.deployId = deployId;
		this.userId = userId;
		this.middlewareId = middlewareId;
		this.instanceId = instanceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_task
	 * @mbg.generated
	 */
	public CommonTask() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_task.id
	 * @return  the value of common_task.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_task.id
	 * @param id  the value for common_task.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_task.name
	 * @return  the value of common_task.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_task.name
	 * @param name  the value for common_task.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_task.version
	 * @return  the value of common_task.version
	 * @mbg.generated
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_task.version
	 * @param version  the value for common_task.version
	 * @mbg.generated
	 */
	public void setVersion(String version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_task.rule
	 * @return  the value of common_task.rule
	 * @mbg.generated
	 */
	public String getRule() {
		return rule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_task.rule
	 * @param rule  the value for common_task.rule
	 * @mbg.generated
	 */
	public void setRule(String rule) {
		this.rule = rule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_task.deploy_id
	 * @return  the value of common_task.deploy_id
	 * @mbg.generated
	 */
	public Long getDeployId() {
		return deployId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_task.deploy_id
	 * @param deployId  the value for common_task.deploy_id
	 * @mbg.generated
	 */
	public void setDeployId(Long deployId) {
		this.deployId = deployId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_task.user_id
	 * @return  the value of common_task.user_id
	 * @mbg.generated
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_task.user_id
	 * @param userId  the value for common_task.user_id
	 * @mbg.generated
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_task.middleware_id
	 * @return  the value of common_task.middleware_id
	 * @mbg.generated
	 */
	public Long getMiddlewareId() {
		return middlewareId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_task.middleware_id
	 * @param middlewareId  the value for common_task.middleware_id
	 * @mbg.generated
	 */
	public void setMiddlewareId(Long middlewareId) {
		this.middlewareId = middlewareId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_task.instance_id
	 * @return  the value of common_task.instance_id
	 * @mbg.generated
	 */
	public Long getInstanceId() {
		return instanceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_task.instance_id
	 * @param instanceId  the value for common_task.instance_id
	 * @mbg.generated
	 */
	public void setInstanceId(Long instanceId) {
		this.instanceId = instanceId;
	}
}