package net.wicp.tams.app.duckula.controller.bean.models;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table common_task
 */
public class CommonTask {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column common_task.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * Database Column Remarks: 监听名称 This field was generated by MyBatis Generator. This field corresponds to the database column common_task.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * Database Column Remarks: duckula监听的版本 This field was generated by MyBatis Generator. This field corresponds to the database column common_task.version
	 * @mbg.generated
	 */
	private String version;
	/**
	 * Database Column Remarks: 部署的名称空间 This field was generated by MyBatis Generator. This field corresponds to the database column common_task.namespace
	 * @mbg.generated
	 */
	private String namespace;
	/**
	 * Database Column Remarks: 规则 This field was generated by MyBatis Generator. This field corresponds to the database column common_task.rule
	 * @mbg.generated
	 */
	private String rule;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_task
	 * @mbg.generated
	 */
	public CommonTask(Integer id, String name, String version, String namespace, String rule) {
		this.id = id;
		this.name = name;
		this.version = version;
		this.namespace = namespace;
		this.rule = rule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_task
	 * @mbg.generated
	 */
	public CommonTask() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_task.id
	 * @return  the value of common_task.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_task.id
	 * @param id  the value for common_task.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_task.name
	 * @return  the value of common_task.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_task.name
	 * @param name  the value for common_task.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_task.version
	 * @return  the value of common_task.version
	 * @mbg.generated
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_task.version
	 * @param version  the value for common_task.version
	 * @mbg.generated
	 */
	public void setVersion(String version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_task.namespace
	 * @return  the value of common_task.namespace
	 * @mbg.generated
	 */
	public String getNamespace() {
		return namespace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_task.namespace
	 * @param namespace  the value for common_task.namespace
	 * @mbg.generated
	 */
	public void setNamespace(String namespace) {
		this.namespace = namespace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_task.rule
	 * @return  the value of common_task.rule
	 * @mbg.generated
	 */
	public String getRule() {
		return rule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_task.rule
	 * @param rule  the value for common_task.rule
	 * @mbg.generated
	 */
	public void setRule(String rule) {
		this.rule = rule;
	}
}