package net.wicp.tams.app.duckula.controller.bean.models;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table common_middleware
 */
public class CommonMiddleware {

	/**
	 * Database Column Remarks: id This field was generated by MyBatis Generator. This field corresponds to the database column common_middleware.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * Database Column Remarks: 名称 This field was generated by MyBatis Generator. This field corresponds to the database column common_middleware.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * Database Column Remarks: 配置类型：ES/Mysql/Kafka This field was generated by MyBatis Generator. This field corresponds to the database column common_middleware.middleware_type
	 * @mbg.generated
	 */
	private String middlewareType;
	/**
	 * Database Column Remarks: 中间件版本 This field was generated by MyBatis Generator. This field corresponds to the database column common_middleware.version
	 * @mbg.generated
	 */
	private String version;
	/**
	 * Database Column Remarks: 所属用户 This field was generated by MyBatis Generator. This field corresponds to the database column common_middleware.user_id
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * Database Column Remarks: 所属公司 This field was generated by MyBatis Generator. This field corresponds to the database column common_middleware.com_id
	 * @mbg.generated
	 */
	private String comId;
	/**
	 * Database Column Remarks: 主机，逗号隔开 This field was generated by MyBatis Generator. This field corresponds to the database column common_middleware.host
	 * @mbg.generated
	 */
	private String host;
	/**
	 * Database Column Remarks: 端口，逗号隔开 This field was generated by MyBatis Generator. This field corresponds to the database column common_middleware.port
	 * @mbg.generated
	 */
	private String port;
	/**
	 * Database Column Remarks: 用户名 This field was generated by MyBatis Generator. This field corresponds to the database column common_middleware.username
	 * @mbg.generated
	 */
	private String username;
	/**
	 * Database Column Remarks: 密码 This field was generated by MyBatis Generator. This field corresponds to the database column common_middleware.password
	 * @mbg.generated
	 */
	private String password;
	/**
	 * Database Column Remarks: 真实配置 This field was generated by MyBatis Generator. This field corresponds to the database column common_middleware.config
	 * @mbg.generated
	 */
	private String config;
	/**
	 * Database Column Remarks: 备注 This field was generated by MyBatis Generator. This field corresponds to the database column common_middleware.remark
	 * @mbg.generated
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_middleware
	 * @mbg.generated
	 */
	public CommonMiddleware(Long id, String name, String middlewareType, String version, String userId, String comId,
			String host, String port, String username, String password, String config, String remark) {
		this.id = id;
		this.name = name;
		this.middlewareType = middlewareType;
		this.version = version;
		this.userId = userId;
		this.comId = comId;
		this.host = host;
		this.port = port;
		this.username = username;
		this.password = password;
		this.config = config;
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table common_middleware
	 * @mbg.generated
	 */
	public CommonMiddleware() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_middleware.id
	 * @return  the value of common_middleware.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_middleware.id
	 * @param id  the value for common_middleware.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_middleware.name
	 * @return  the value of common_middleware.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_middleware.name
	 * @param name  the value for common_middleware.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_middleware.middleware_type
	 * @return  the value of common_middleware.middleware_type
	 * @mbg.generated
	 */
	public String getMiddlewareType() {
		return middlewareType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_middleware.middleware_type
	 * @param middlewareType  the value for common_middleware.middleware_type
	 * @mbg.generated
	 */
	public void setMiddlewareType(String middlewareType) {
		this.middlewareType = middlewareType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_middleware.version
	 * @return  the value of common_middleware.version
	 * @mbg.generated
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_middleware.version
	 * @param version  the value for common_middleware.version
	 * @mbg.generated
	 */
	public void setVersion(String version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_middleware.user_id
	 * @return  the value of common_middleware.user_id
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_middleware.user_id
	 * @param userId  the value for common_middleware.user_id
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_middleware.com_id
	 * @return  the value of common_middleware.com_id
	 * @mbg.generated
	 */
	public String getComId() {
		return comId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_middleware.com_id
	 * @param comId  the value for common_middleware.com_id
	 * @mbg.generated
	 */
	public void setComId(String comId) {
		this.comId = comId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_middleware.host
	 * @return  the value of common_middleware.host
	 * @mbg.generated
	 */
	public String getHost() {
		return host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_middleware.host
	 * @param host  the value for common_middleware.host
	 * @mbg.generated
	 */
	public void setHost(String host) {
		this.host = host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_middleware.port
	 * @return  the value of common_middleware.port
	 * @mbg.generated
	 */
	public String getPort() {
		return port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_middleware.port
	 * @param port  the value for common_middleware.port
	 * @mbg.generated
	 */
	public void setPort(String port) {
		this.port = port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_middleware.username
	 * @return  the value of common_middleware.username
	 * @mbg.generated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_middleware.username
	 * @param username  the value for common_middleware.username
	 * @mbg.generated
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_middleware.password
	 * @return  the value of common_middleware.password
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_middleware.password
	 * @param password  the value for common_middleware.password
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_middleware.config
	 * @return  the value of common_middleware.config
	 * @mbg.generated
	 */
	public String getConfig() {
		return config;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_middleware.config
	 * @param config  the value for common_middleware.config
	 * @mbg.generated
	 */
	public void setConfig(String config) {
		this.config = config;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column common_middleware.remark
	 * @return  the value of common_middleware.remark
	 * @mbg.generated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column common_middleware.remark
	 * @param remark  the value for common_middleware.remark
	 * @mbg.generated
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}