package net.wicp.tams.app.duckula.controller.bean.models;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table common_dump
 */
public class CommonDump {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_dump.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   监听名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_dump.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   duckula监听的版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_dump.version
     *
     * @mbg.generated
     */
    private String version;

    /**
     * Database Column Remarks:
     *   部署的名称空间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_dump.namespace
     *
     * @mbg.generated
     */
    private String namespace;

    /**
     * Database Column Remarks:
     *   规则
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_dump.rule
     *
     * @mbg.generated
     */
    private String rule;

    /**
     * Database Column Remarks:
     *   部署id，common_deploy表的id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_dump.deploy_id
     *
     * @mbg.generated
     */
    private Long deployId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_dump
     *
     * @mbg.generated
     */
    public CommonDump(Long id, String name, String version, String namespace, String rule, Long deployId) {
        this.id = id;
        this.name = name;
        this.version = version;
        this.namespace = namespace;
        this.rule = rule;
        this.deployId = deployId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_dump
     *
     * @mbg.generated
     */
    public CommonDump() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_dump.id
     *
     * @return the value of common_dump.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_dump.id
     *
     * @param id the value for common_dump.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_dump.name
     *
     * @return the value of common_dump.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_dump.name
     *
     * @param name the value for common_dump.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_dump.version
     *
     * @return the value of common_dump.version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_dump.version
     *
     * @param version the value for common_dump.version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_dump.namespace
     *
     * @return the value of common_dump.namespace
     *
     * @mbg.generated
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_dump.namespace
     *
     * @param namespace the value for common_dump.namespace
     *
     * @mbg.generated
     */
    public void setNamespace(String namespace) {
        this.namespace = namespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_dump.rule
     *
     * @return the value of common_dump.rule
     *
     * @mbg.generated
     */
    public String getRule() {
        return rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_dump.rule
     *
     * @param rule the value for common_dump.rule
     *
     * @mbg.generated
     */
    public void setRule(String rule) {
        this.rule = rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_dump.deploy_id
     *
     * @return the value of common_dump.deploy_id
     *
     * @mbg.generated
     */
    public Long getDeployId() {
        return deployId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_dump.deploy_id
     *
     * @param deployId the value for common_dump.deploy_id
     *
     * @mbg.generated
     */
    public void setDeployId(Long deployId) {
        this.deployId = deployId;
    }
}