package net.wicp.tams.app.duckula.controller.bean.models;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_global
 */
public class SysGlobal {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_global.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * Database Column Remarks: 分组 This field was generated by MyBatis Generator. This field corresponds to the database column sys_global.group_name
	 * @mbg.generated
	 */
	private String groupName;
	/**
	 * Database Column Remarks: 配置名 This field was generated by MyBatis Generator. This field corresponds to the database column sys_global.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * Database Column Remarks: 配置值 This field was generated by MyBatis Generator. This field corresponds to the database column sys_global.value
	 * @mbg.generated
	 */
	private String value;
	/**
	 * Database Column Remarks: 编辑类型，默认为validatebox This field was generated by MyBatis Generator. This field corresponds to the database column sys_global.type
	 * @mbg.generated
	 */
	private String type;
	/**
	 * Database Column Remarks: 验证类型 This field was generated by MyBatis Generator. This field corresponds to the database column sys_global.valid_type
	 * @mbg.generated
	 */
	private String validType;
	/**
	 * Database Column Remarks: 排序 This field was generated by MyBatis Generator. This field corresponds to the database column sys_global.order_index
	 * @mbg.generated
	 */
	private Integer orderIndex;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_global
	 * @mbg.generated
	 */
	public SysGlobal(Long id, String groupName, String name, String value, String type, String validType,
			Integer orderIndex) {
		this.id = id;
		this.groupName = groupName;
		this.name = name;
		this.value = value;
		this.type = type;
		this.validType = validType;
		this.orderIndex = orderIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_global
	 * @mbg.generated
	 */
	public SysGlobal() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_global.id
	 * @return  the value of sys_global.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_global.id
	 * @param id  the value for sys_global.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_global.group_name
	 * @return  the value of sys_global.group_name
	 * @mbg.generated
	 */
	public String getGroupName() {
		return groupName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_global.group_name
	 * @param groupName  the value for sys_global.group_name
	 * @mbg.generated
	 */
	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_global.name
	 * @return  the value of sys_global.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_global.name
	 * @param name  the value for sys_global.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_global.value
	 * @return  the value of sys_global.value
	 * @mbg.generated
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_global.value
	 * @param value  the value for sys_global.value
	 * @mbg.generated
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_global.type
	 * @return  the value of sys_global.type
	 * @mbg.generated
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_global.type
	 * @param type  the value for sys_global.type
	 * @mbg.generated
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_global.valid_type
	 * @return  the value of sys_global.valid_type
	 * @mbg.generated
	 */
	public String getValidType() {
		return validType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_global.valid_type
	 * @param validType  the value for sys_global.valid_type
	 * @mbg.generated
	 */
	public void setValidType(String validType) {
		this.validType = validType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_global.order_index
	 * @return  the value of sys_global.order_index
	 * @mbg.generated
	 */
	public Integer getOrderIndex() {
		return orderIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_global.order_index
	 * @param orderIndex  the value for sys_global.order_index
	 * @mbg.generated
	 */
	public void setOrderIndex(Integer orderIndex) {
		this.orderIndex = orderIndex;
	}
}