package net.wicp.tams.app.duckula.controller.bean.models;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_global
 */
public class SysGlobal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_global.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   配置名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_global.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   配置值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_global.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_global
     *
     * @mbg.generated
     */
    public SysGlobal(Long id, String name, String value) {
        this.id = id;
        this.name = name;
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_global
     *
     * @mbg.generated
     */
    public SysGlobal() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_global.id
     *
     * @return the value of sys_global.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_global.id
     *
     * @param id the value for sys_global.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_global.name
     *
     * @return the value of sys_global.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_global.name
     *
     * @param name the value for sys_global.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_global.value
     *
     * @return the value of sys_global.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_global.value
     *
     * @param value the value for sys_global.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value;
    }
}